"""PRD-010 slice 1 — the identity harness for the bundled example parts.

Nothing here ships to a user. This module writes down what the three
``construction`` parts (plus ``rocketry/flange`` and
``prototyping/enclosure_lid`` as controls) measure and tessellate to *today*,
before ``toolkit.patterns``/``toolkit.holes`` exist, so slice 7's rewrite of
those scripts cannot quietly change the geometry and slices 3/4 cannot quietly
change what a hole is.

**The criterion this harness encodes.** PRD-010's AC1 asks the rewrite to keep
"the same content-hash mesh-cache entries", which is impossible: the cache key
hashes the *script text* (``service._cache_key``), so any rewrite whatsoever
mints a new key. The design spec restates it, and this is the restated form:

  (a) every metric equal to the golden — ``volume_mm3``, ``area_mm2``,
      ``mass_g``, ``bbox`` and ``center_of_mass`` at ``rel=1e-9``, and
      ``n_faces``/``n_edges``/``n_solids`` exactly; **and**
  (b) a **byte-identical ``.acm`` payload** under the new key.

(b) is the load-bearing half and it is not implied by (a): measured on
``gusset_plate`` through the worker at its shipped params, cutting the same
holes with ``part - Compound(cylinders)`` instead of
``Locations(...)``/``Hole(...)`` gives the same face and edge counts and a
volume that differs in the last bits (320571.0948520879 vs
320571.09485208784 — a relative 2e-16, well inside ``rel=1e-9``) and a
**different** mesh (``56b50449…`` vs ``a00ec644…``). Only the route that
re-enters a ``BuildPart`` and ``add()``s the caller's part reproduces the
shipped bytes — measured byte-identical on all three parts below, through the
worker (changelog 0147, spike S1). A golden that checked metrics alone would
pass the wrong implementation.

**The goldens are literals below**, generated by running this module once
against the committed examples — not a JSON fixture nobody reads. If a golden
moves, that is a finding to explain in the changelog, never a number to
re-baseline.

``measure_part`` and ``script_acm_sha256`` are the reusable half: slices 3, 4
and 7 assert byte-identity through them rather than growing a second harness.
"""

import hashlib
import shutil
from pathlib import Path

import pytest

from agentcad.core.service import MESH_TOLERANCE

from .conftest import make_test_service

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"

# (example project, part id) -> the measurement taken on the committed script
# at the params stored in the example's project.json (not the script defaults —
# the goldens describe the bundled projects as they ship). `acm_sha256` is the
# full tessellated payload at MESH_TOLERANCE, i.e. the bytes the browser and
# every consumer of the mesh cache receive.
#
# A sha golden is a statement about this toolchain: the pinned build123d/OCCT
# wheels on this platform. If ALL FIVE move together, suspect the toolchain and
# say so; if ONE moves, that is a geometry change and the point of the harness.
GOLDENS: dict[tuple[str, str], dict] = {
    ('construction', 'angle_bracket'): {
        'volume_mm3': 130460.5316883793,
        'area_mm2': 32537.22113490002,
        'mass_g': 1024.1151737537773,
        'bbox': {'max': [90.0, 0.0, 90.0], 'min': [0.0, -80.0, 0.0]},
        'center_of_mass': [25.97291826384933, -40.000000000000014,
                           25.972918263849323],
        'n_faces': 13,
        'n_edges': 33,
        'n_solids': 1,
        'is_valid': True,
        'acm_bytes': 26336,
        'acm_sha256':
            '5a0eda299d7100918b18d10296d7945d0d223e61460247249ed1d06b63999a99',
    },
    ('construction', 'base_plate'): {
        'volume_mm3': 1704892.5684204306,
        'area_mm2': 206205.09697379713,
        'mass_g': 13383.40666210038,
        'bbox': {'max': [150.0, 150.0, 20.0], 'min': [-150.0, -150.0, 0.0]},
        'center_of_mass': [-2.088644971197563e-15, -2.9279039413642022e-15,
                           9.874625531274361],
        'n_faces': 31,
        'n_edges': 84,
        'n_solids': 1,
        'is_valid': True,
        'acm_bytes': 34676,
        'acm_sha256':
            '238c8ceb7d3222e6c8c38066083007aed6f3825da449782ced5efd25370195a7',
    },
    ('construction', 'gusset_plate'): {
        'volume_mm3': 320571.0948520879,
        'area_mm2': 78194.46419985406,
        'mass_g': 2516.48309458889,
        'bbox': {'max': [136.47160900000003, 176.471609, 10.0],
                 'min': [-136.471609, -1.517666744069012e-14, 0.0]},
        'center_of_mass': [-2.9051982214590884e-15, 99.00114642211845,
                           5.000000000000009],
        'n_faces': 20,
        'n_edges': 54,
        'n_solids': 1,
        'is_valid': True,
        'acm_bytes': 72044,
        'acm_sha256':
            '56b50449ac4e6bc1a43272d726db5f03fbc3cbcdb35df5a36d94b9294519470b',
    },
    ('prototyping', 'enclosure_lid'): {
        'volume_mm3': 19086.934338601866,
        'area_mm2': 14614.057589913713,
        'mass_g': 19.85041171214594,
        'bbox': {'max': [50.0, 30.0, 3.0], 'min': [-50.0, -30.0, -3.0]},
        'center_of_mass': [-7.664521718624591e-14, 1.695678987148393e-10,
                           1.242820277843059],
        'n_faces': 48,
        'n_edges': 128,
        'n_solids': 1,
        'is_valid': True,
        'acm_bytes': 83092,
        'acm_sha256':
            '7c8698c9cfe08391e4e985e0f7e219c075cd208ce1970274a50a1e0f2f86dd9d',
    },
    ('rocketry', 'flange'): {
        'volume_mm3': 124081.24194168134,
        'area_mm2': 30061.107996242794,
        'mass_g': 992.6499355334507,
        'bbox': {'max': [70.0, 70.0, 14.0], 'min': [-70.0, -70.0, 0.0]},
        'center_of_mass': [-1.275390829686155e-15, 6.222815936994435e-16,
                           6.999999999999998],
        'n_faces': 16,
        'n_edges': 38,
        'n_solids': 1,
        'is_valid': True,
        'acm_bytes': 94924,
        'acm_sha256':
            'e983be0745dc9a39ddf851ac03b9a13ef99d7c47b060bad755e4bd842f02599f',
    },
}

# rel=1e-9 for floats: the restated AC1 tolerance. ABS is the floor a *relative*
# tolerance cannot supply — three of the goldens' coordinates are a nominal zero
# carrying float noise (`bbox.min.y = -1.5e-14` on the gusset plate), and
# `rel=1e-9` against those demands agreement to 1e-23. 1e-9 mm is a nanometre.
# Integer topology counts are compared exactly: a face count has no error bars.
REL = 1e-9
ABS = 1e-9
_FLOAT_KEYS = ("volume_mm3", "area_mm2", "mass_g")
_EXACT_KEYS = ("n_faces", "n_edges", "n_solids", "is_valid")


def measure_part(service, project: str, part_id: str) -> dict:
    """Rebuild one part at its stored params and return the golden record.

    Goes through ``service._rebuild`` rather than the kernel directly so the
    measurement covers the real pipeline — the cache key, the sidecar and the
    ``.acm`` the mesh cache actually serves.
    """
    result = service._rebuild(project, part_id)
    assert result["ok"], f"{project}/{part_id} did not build: {result.get('error')}"
    metrics = result["metrics"]
    mesh = service.store.cache_dir(project) / f"{result['cache_key']}.acm"
    payload = mesh.read_bytes()
    return {
        "volume_mm3": metrics["volume_mm3"],
        "area_mm2": metrics["area_mm2"],
        "mass_g": metrics["mass_g"],
        "bbox": metrics["bbox"],
        "center_of_mass": metrics["center_of_mass"],
        "n_faces": metrics["n_faces"],
        "n_edges": metrics["n_edges"],
        "n_solids": metrics["n_solids"],
        "is_valid": metrics["is_valid"],
        "acm_bytes": len(payload),
        "acm_sha256": hashlib.sha256(payload).hexdigest(),
    }


def script_acm_sha256(kernel, script: str, params: dict | None = None,
                      *, mesh_path: Path, tolerance: float = MESH_TOLERANCE,
                      density_g_cm3: float = 1.0) -> tuple[str, dict]:
    """Build one script straight through the worker; return (sha256, metrics).

    The probe slices 3/4/7 use to assert "the helper form is byte-identical to
    the hand-written form": two scripts, one kernel, the same tolerance, and a
    comparison of the tessellated payload — which is the only comparison that
    can tell the two routes apart (see the module docstring).
    """
    result = kernel.request("build", {
        "script": script,
        "params": params or {},
        "mesh_path": str(mesh_path),
        "tolerance": tolerance,
        "density_g_cm3": density_g_cm3,
    }, timeout_s=300.0)
    return hashlib.sha256(Path(mesh_path).read_bytes()).hexdigest(), result["metrics"]


def assert_matches_golden(measured: dict, golden: dict, label: str) -> None:
    """Restated AC1 in one call: metrics at rel=1e-9, then the mesh bytes."""
    for key in _FLOAT_KEYS:
        assert measured[key] == pytest.approx(golden[key], rel=REL, abs=ABS), \
            f"{label}: {key} moved {golden[key]!r} -> {measured[key]!r}"
    for axis in ("min", "max"):
        assert measured["bbox"][axis] == pytest.approx(
            golden["bbox"][axis], rel=REL, abs=ABS), f"{label}: bbox.{axis} moved"
    assert measured["center_of_mass"] == pytest.approx(
        golden["center_of_mass"], rel=REL, abs=ABS), \
        f"{label}: center_of_mass moved"
    for key in _EXACT_KEYS:
        assert measured[key] == golden[key], \
            f"{label}: {key} moved {golden[key]!r} -> {measured[key]!r}"
    assert measured["acm_bytes"] == golden["acm_bytes"], (
        f"{label}: the .acm is a different size ({golden['acm_bytes']} -> "
        f"{measured['acm_bytes']} bytes) — the triangle count changed, so this "
        f"is a geometry or tessellation change, not a reordering"
    )
    assert measured["acm_sha256"] == golden["acm_sha256"], (
        f"{label}: the .acm payload changed ({golden['acm_sha256'][:16]} -> "
        f"{measured['acm_sha256'][:16]}). Metrics may still match: a route that "
        f"produces identical volume and face count can tessellate to different "
        f"bytes. Report the difference, do not re-baseline."
    )


@pytest.fixture(scope="module")
def service(kernel, tmp_path_factory):
    return make_test_service(tmp_path_factory.mktemp("projects"), kernel)


@pytest.fixture(scope="module")
def opened(service, tmp_path_factory):
    """Every golden example opened from a COPY — examples/ is never mutated."""
    root = tmp_path_factory.mktemp("golden")
    names = {}
    for project in sorted({proj for proj, _part in GOLDENS}):
        src = EXAMPLES_DIR / project
        dest = root / project
        shutil.copytree(src, dest,
                        ignore=shutil.ignore_patterns(".cache", "exports"))
        names[project] = service.open_project(str(dest))["name"]
    return service, names


@pytest.mark.integration
@pytest.mark.parametrize("project,part_id", sorted(GOLDENS),
                         ids=lambda v: str(v))
def test_bundled_part_matches_golden(opened, project, part_id):
    """Restated AC1's gate: the committed examples still measure and
    tessellate to what they measured when this harness was written."""
    service, names = opened
    measured = measure_part(service, names[project], part_id)
    assert_matches_golden(measured, GOLDENS[(project, part_id)],
                          f"{project}/{part_id}")


@pytest.mark.integration
def test_goldens_cover_every_construction_part(opened):
    """The construction example is what slice 7 rewrites, so a part added to it
    without a golden must fail here rather than sail through unmeasured."""
    service, names = opened
    covered = {part for proj, part in GOLDENS if proj == "construction"}
    parts = {p["id"] for p in service.get_project(names["construction"])["parts"]}
    assert parts == covered, f"construction parts without a golden: {parts - covered}"


@pytest.mark.integration
def test_the_rewritten_construction_parts_carry_hole_records(kernel, tmp_path):
    """Slice 7's *other* half, and the one the goldens above cannot see.

    A byte-identity gate is passed trivially by an edit that changes nothing.
    What makes the rewrite worth doing is that every bolt hole in the bundled
    ``construction`` example is now a machine-readable record — which is what
    reaches the drawing callouts (slice 6) and PRD-021's DFM rules. If someone
    reverts a script to a hand-rolled ``Locations``/``Hole`` block, the goldens
    stay green and this fails.

    ``base_plate``'s anchor **slots** are not holes, so it carries no records
    at all. It is read with ``.get`` on purpose: "declares none" (``null``) and
    "not harvested" (key **absent**) are different facts, and which one this
    part gives depends on whether the session-scoped worker already has its
    shape cached from an earlier test — a harvest that took a shape-cache hit
    measured nothing and must not persist an empty answer (changelog 0151).
    The assertion here is the part they agree on: no records.
    """
    from agentcad.core.tools import build_registry

    service = make_test_service(tmp_path / "projects", kernel)
    dest = tmp_path / "construction"
    shutil.copytree(EXAMPLES_DIR / "construction", dest,
                    ignore=shutil.ignore_patterns(".cache", "exports"))
    name = service.open_project(str(dest))["name"]
    build_registry(service)          # installs the hole-metadata rebuild seam

    gusset = service._rebuild(name, "gusset_plate")
    assert [(r["family"], r["designation"], r["count"])
            for r in gusset["holes"]] == [("drilled", "⌀18", 12)]

    bracket = service._rebuild(name, "angle_bracket")
    assert [(r["designation"], r["count"]) for r in bracket["holes"]] == [
        ("⌀14", 2), ("⌀14", 2)]

    assert service._rebuild(name, "base_plate").get("holes") is None


@pytest.mark.integration
def test_two_routes_to_one_geometry_differ_in_bytes(kernel, tmp_path):
    """The evidence that (b) is a real constraint and not implied by (a).

    Cutting one hole with ``Locations``/``Hole`` and with a ``Compound``
    subtraction gives the same volume and the same face count, and a different
    mesh. This is what makes ``acm_sha256`` worth asserting; if it ever stops
    being true, the harness has lost its teeth and slice 7's gate is weaker
    than the changelog says.
    """
    builder = (
        "from build123d import *\n"
        'PARAMS = {"d": {"default": 8.0, "min": 1.0, "max": 20.0, "unit": "mm",\n'
        '                "description": "hole diameter"}}\n'
        "def build(p):\n"
        "    with BuildPart() as part:\n"
        "        Box(60, 40, 10)\n"
        "        with Locations((15, 10), (-15, -10)):\n"
        "            Hole(radius=p.d / 2)\n"
        "    return part.part\n"
    )
    compound = (
        "from build123d import *\n"
        'PARAMS = {"d": {"default": 8.0, "min": 1.0, "max": 20.0, "unit": "mm",\n'
        '                "description": "hole diameter"}}\n'
        "def build(p):\n"
        "    plate = Box(60, 40, 10)\n"
        "    cyls = [Cylinder(p.d / 2, 40).moved(Location(pt))\n"
        "            for pt in ((15, 10, 0), (-15, -10, 0))]\n"
        "    return plate - Compound(children=cyls)\n"
    )
    sha_a, m_a = script_acm_sha256(kernel, builder, mesh_path=tmp_path / "a.acm")
    sha_b, m_b = script_acm_sha256(kernel, compound, mesh_path=tmp_path / "b.acm")
    assert m_a["n_faces"] == m_b["n_faces"]
    assert m_a["volume_mm3"] == pytest.approx(m_b["volume_mm3"], rel=REL)
    assert sha_a != sha_b, (
        "the two construction routes now tessellate identically; the .acm "
        "assertion in this harness no longer distinguishes them"
    )
